<?php

/**
 * AlgoliaProductRecommendations
 *
 * Algolia product recommendations UI
 *
 * @package ImaginationMedia\AlgoliaProductRecommendations
 * @author Vasilii Burlacu <vasilii@imaginationmedia.com>
 * @copyright Copyright (c) 2022 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 */

use ImaginationMedia\AlgoliaProductRecommendations\ViewModel\ProductRecommendationsViewModel;
use ImaginationMedia\AlgoliaProductRecommendations\ViewModel\RecommendationsViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ProductRecommendationsViewModel $relatedProducts */
$relatedProducts = $block->getData('relatedProductsViewModel');
/** @var RecommendationsViewModel $recommendationsViewModel */
$recommendationsViewModel = $block->getData('recommendationsViewModel');

if (!$recommendationsViewModel->isEnabled() || !$relatedProducts->getProductId()) {
    return;
}
?>

<script src="https://cdn.jsdelivr.net/npm/@algolia/recommend"></script>
<script>
    const algoliarecommend = window['@algolia/recommend'];
    const client = algoliarecommend(
        '<?= $escaper->escapeJs($recommendationsViewModel->getApplicationId()) ?>',
        '<?= $escaper->escapeJs($recommendationsViewModel->getSearchOnlyAPIKey()) ?>'
    );

    client.getRecommendations([
        {
            indexName: '<?= $escaper->escapeJs($recommendationsViewModel->getIndexName()) ?>',
            objectID: '<?= $escaper->escapeJs($relatedProducts->getProductId()) ?>',
            model: 'related-products',
            maxRecommendations: 10
        },
    ])
    .then(({ results }) => {
        console.log(results);
    })
    .catch(err => {
        console.log(err);
    });
</script>
