<?php

/**
 * AlgoliaProductRecommendations
 *
 * Algolia product recommendations UI
 *
 * @see https://www.algolia.com/doc/api-client/methods/recommend/?client=javascript
 * @see https://www.algolia.com/doc/api-reference/api-methods/get-recommendations/?client=javascript
 *
 * @package ImaginationMedia\AlgoliaProductRecommendations
 * @author Vasilii Burlacu <vasilii@imaginationmedia.com>
 * @copyright Copyright (c) 2022 Imagination Media (https://www.imaginationmedia.com/)
 * @license https://opensource.org/licenses/OSL-3.0.php Open Software License 3.0
 *
 */

declare(strict_types=1);

use ImaginationMedia\AlgoliaProductRecommendations\ViewModel\RecommendationsViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var RecommendationsViewModel $recommendationsViewModel */
$recommendationsViewModel = $block->getData('recommendationsViewModel');

if (!$recommendationsViewModel->isEnabled()) {
    return;
}
?>

<script>
    /**
     * @typedef {Object} hit The product
     *
     * @property {string} name Product's name
     * @property {string} sku Product's SKU
     * @property {string} image_url Product's main image
     * @property {string} thumbnail_url Product's thumbnail image
     * @property ... any other product attribute passed to Algolia
     */

    /**
     * @typedef AlgoliaRecommendClient
     * @property {Function} getRecommendations
     * @see https://www.algolia.com/doc/api-reference/api-methods/get-recommendations/#parameters
     */

    function algoliaRecommendations() {
        function loadScript (url) {
            let script = document.createElement('script');
            script.setAttribute('type', 'text/javascript');
            script.setAttribute('src', url);
            script.setAttribute('id', 'algolia-recommend');
            document.head.append(script);

            return new Promise((resolve) => script.addEventListener('load', resolve));
        }

        return {
            fetchProductsInitially: true,
            nbHits: 0,
            hits: [],
            initialized: false,
            algoliaRecommendClient: null,
            additionalApiParams: {},
            recommendationsModel: '<?= $escaper->escapeJs($block->getData('recommendationModel')) ?>',
            recommendationsLimit: <?= $escaper->escapeJs((int)$block->getData('productLimit')) ?>,
            indexName: '<?= $escaper->escapeJs($recommendationsViewModel->getIndexName()) ?>',

            init() {
                this.loadScripts();
            },

            /**
             * Loading on the page the Algolia recommend javascript
             */
            loadScripts() {
                if (this.initialized) {
                    return;
                }

                if (document.getElementById('algolia-recommend')) {
                    this.fetchProductsInitially && this.fetchProducts();
                } else {
                    loadScript('https://cdn.jsdelivr.net/npm/@algolia/recommend').then(() => {
                        this.algoliaRecommendClient = window['@algolia/recommend'](
                            '<?= $escaper->escapeJs($recommendationsViewModel->getApplicationId()) ?>',
                            '<?= $escaper->escapeJs($recommendationsViewModel->getSearchOnlyAPIKey()) ?>'
                        );

                        this.fetchProductsInitially && this.fetchProducts();
                    });
                }

                this.initialized = true;
            },

            /**
             * Does a request to Algolia's API to fetch the products
             */
            fetchProducts() {
                this.algoliaRecommendClient.getRecommendations(this.getRecommendationRequests())
                .then(({ results }) => this.saveApiResponseData(results))
                .catch(err => console.error(err));
            },

            getRecommendationRequests() {
                return [];

                /**
                 * Example of return:
                 *
                 * return [
                 *     Object.assign({
                 *             indexName: this.indexName,
                 *             objectID: 17833,
                 *             model: this.recommendationsModel,
                 *             maxRecommendations: this.recommendationsLimit
                 *         }
                 *     )
                 * ]
                 */
            },

            saveApiResponseData(results) {
                /**
                 * Default behaviour is to save the first given result from the API.
                 * Might change for other cases, like Shopping Cart page.
                 */

                const data = results[0] || null;

                if (!data) {
                    return;
                }

                this.nbHits = data.nbHits;
                this.hits = data.hits;
            },

            eventListeners: {
                // Placeholder for later usage & customisation
            }
        }
    }
</script>
